[Monday.1]
Subject = "Физра"
Teacher = "Варушин А.В."
Start = "13.30"
End = "15.00"
Class = [ "4402/1", "Ломо",]

[Thursday.1]
Subject = "Информатика"
Teacher = "Миняев И.А."
Start = "11.30"
End = "13.00"
Class = [ "1328", "ГК",]

[Thursday.2]
Subject = "Информатика"
Teacher = "Миняев И.А."
Start = "13.30"
End = "15.00"
Class = [ "1328", "ГК",]

[Thursday.3]
Subject = "ОПД"
Teacher = "Ткешелашвили Н.М."
Start = "15.30"
End = "17.00"
Class = [ "2435/3", "ГК",]

[Thursday.4]
Subject = "ОПД"
Teacher = "Ткешелашвили Н.М."
Start = "17.10"
End = "18.40"
Class = [ "2435/3", "ГК",]
